train_dir: /mnt/lustre/zongdaoming/GNN-XMC/model_test/data/in_domain_train.tsv
epochs: 5
lr: 0.00005
weight_decay_rate: 0.001
saver_train: train_acc_set_5e_5_train.pkl
saver_test: test_acc_set_5e_5_test.pkl